export default {
  accuweather: {
    name: "AccuWeather",
    app_icon: "icon_accuweather.png",
    launcher: "package",
    package: "com.accuweather.android",
  },
  allrecipes: {
    name: "AllRecipes",
    app_icon: "icon_allrecipes.png",
    launcher: "package",
    package: "com.allrecipes.spinner.free",
  },
  amazon_music: {
    name: "Amazon Music",
    app_icon: "icon_amazon_music.png",
    launcher: "uri_scheme",
    uri_scheme: "amznmp3://",
  },
  amazon_shopping: {
    name: "Amazon Shopping",
    app_icon: "icon_amazon_shopping.png",
    launcher: "uri_scheme",
    package: "com.amazon.windowshop",
    uri_scheme: "amazon://",
  },
  amcrest_smart_home: {
    name: "Amcrest Smart Home",
    app_icon: "icon_amcrest_smart_home.png",
    launcher: "package",
    package: "com.mm.android.amcrestsmarthome",
  },
  apple_music: {
    name: "Apple Music",
    app_icon: "icon_apple_music.png",
    launcher: "package",
    package: "com.apple.android.music",
  },
  my_bmw: {
    name: "My BMW",
    app_icon: "icon_bmw.png",
    launcher: "package",
    package: "de.bmw.connected.mobile20.na",
  },
  bond: {
    name: "Bond Home",
    app_icon: "icon_bond.png",
    launcher: "package",
    package: "io.olibra.bondapp",
  },
  calculator: {
    name: "Calculator",
    app_icon: "icon_calculator.png",
    launcher: "package",
    package: "com.google.android.calculator",
  },
  chatgpt: {
    name: "ChatGPT",
    app_icon: "icon_chatgpt.png",
    launcher: "package",
    package: "com.openai.chatgpt",
  },
  chrome: {
    name: "Chrome",
    app_icon: "icon_chrome.png",
    launcher: "uri_scheme",
    uri_scheme: "chrome://",
    package: "com.android.chrome",
  },
  clock_timer: {
    name: "Clock/Timer",
    app_icon: "icon_clock.png",
    launcher: "package",
    package: "com.google.android.deskclock",
  },
  doordash: {
    name: "Doordash",
    app_icon: "icon_doordash.png",
    launcher: "uri_scheme",
    uri_scheme: "doordash://",
    package: "com.dd.dashdash",
  },
  eufy_security: {
    name: "Eufy Security",
    app_icon: "icon_eufy_security.png",
    launcher: "package",
    package: "com.oceanwing.battery.cam",
  },
  grubhub: {
    name: "Grubhub",
    app_icon: "icon_grubhub.png",
    launcher: "uri_scheme",
    uri_scheme: "grubhub://",
    package: "com.grubhub.android",
  },
  home_connect: {
    name: "Home Connect",
    app_icon: "icon_home_connect.png",
    launcher: "package",
    package: "com.bshg.homeconnect.android.release.na",
  },
  hue: {
    name: "Hue",
    app_icon: "icon_hue.png",
    launcher: "package",
    package: "com.philips.lighting.hue2",
  },
  hulu: {
    name: "Hulu",
    app_icon: "icon_hulu.png",
    launcher: "uri_scheme",
    uri_scheme: "hulu://",
    package: "com.hulu.plus",
  },
  irobot: {
    name: "iRobot",
    app_icon: "icon_irobot.png",
    launcher: "package",
    package: "com.irobot.home",
  },
  keurig: {
    name: "Keurig",
    app_icon: "icon_keurig.png",
    launcher: "package",
    package: "com.keurig.kconnect",
  },
  lionchief: {
    name: "LionChief",
    app_icon: "icon_lionchief.png",
    launcher: "package",
    package: "com.lionel.lionchief",
  },
  lutron: {
    name: "Lutron",
    app_icon: "icon_lutron.png",
    launcher: "package",
    package: "com.lutron.mmw",
  },
  myq: {
    name: "MyQ",
    app_icon: "icon_myq.png",
    launcher: "package",
    package: "com.chamberlain.android.liftmaster.myq",
  },
  nest: {
    name: "Nest",
    app_icon: "icon_nest.png",
    launcher: "package",
    package: "com.nest.android",
  },
  netflix: {
    name: "Netflix",
    app_icon: "icon_netflix.png",
    launcher: "package",
    package: "com.netflix.mediaclient",
  },
  pandora: {
    name: "Pandora",
    app_icon: "icon_pandora.png",
    launcher: "uri_scheme",
    uri_scheme: "pandora://",
    package: "com.pandora.android",
  },
  play_store: {
    name: "Play Store",
    app_icon: "mdi:store",
    launcher: "package",
    package: "com.android.vending",
  },
  rachio: {
    name: "Rachio",
    app_icon: "icon_rachio.png",
    launcher: "package",
    package: "com.rachio.iro",
  },
  rainbird: {
    name: "Rainbird",
    app_icon: "icon_rainbird.png",
    launcher: "package",
    package: "com.rainbird",
  },
  ring: {
    name: "Ring",
    app_icon: "icon_ring.png",
    launcher: "uri_scheme",
    uri_scheme: "ring://",
    package: "com.ringapp",
  },
  roku_remote: {
    name: "Roku Remote",
    app_icon: "icon_roku.png",
    launcher: "package",
    package: "com.roku.remote",
  },
  sense: {
    name: "Sense Energy",
    app_icon: "icon_sense.png",
    launcher: "package",
    package: "com.sense.androidclient",
  },
  shazam: {
    name: "Shazam",
    app_icon: "icon_shazam.png",
    launcher: "package",
    package: "com.shazam.android",
  },
  shipt_shopper: {
    name: "Shipt Shopper",
    app_icon: "icon_shipt.png",
    launcher: "package",
    package: "com.shipt.shopper",
  },
  sleepiq: {
    name: "SleepIQ",
    app_icon: "icon_sleepiq.png",
    launcher: "package",
    package: "com.selectcomfort.SleepIQ",
  },
  solitaire: {
    name: "Solitaire",
    app_icon: "icon_solitaire.png",
    launcher: "package",
    package: "com.tripledot.solitaire",
  },
  sonos: {
    name: "Sonos",
    app_icon: "icon_sonos.png",
    launcher: "uri_scheme",
    uri_scheme: "sonos://",
    package: "com.sonos.acr2",
  },
  spotify: {
    name: "Spotify",
    app_icon: "icon_spotify.png",
    launcher: "uri_scheme",
    uri_scheme: "spotify://",
    package: "com.spotify.music",
  },
  tuya_smart: {
    name: "Tuya Smart",
    app_icon: "icon_tuya.png",
    launcher: "package",
    package: "com.tuya.smart",
  },
  uber_eats: {
    name: "Uber Eats",
    app_icon: "icon_uber_eats.png",
    launcher: "package",
    package: "com.ubercab.eats",
  },
  weather_channel: {
    name: "Weather Channel",
    app_icon: "icon_weather_channel.png",
    launcher: "package",
    package: "com.weather.Weather",
  },
  weather_underground: {
    name: "Weather Underground",
    app_icon: "icon_weather_underground.png",
    launcher: "package",
    package: "com.wunderground.android.weather",
  },
  yummly: {
    name: "Yummly Recipes",
    app_icon: "icon_yummly.png",
    launcher: "package",
    package: "com.yummly.android",
  },
};
